services:
  postgres:
    image: 'postgres:latest'
    container_name: 'shipping.service.postgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '${POSTGRES_PORT}:5432'
# Interpolation of .env in compose.yaml -> https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/
