spring.application.name=graphql

spring.graphql.schema.locations=classpath:graphql
spring.graphql.schema.file-extensions=graphql
spring.graphql.http.path=/graphql

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.docker.compose.enabled=true
spring.docker.compose.file=@project.basedir@/compose.yaml
spring.docker.compose.skip.in-tests=false
spring.docker.compose.lifecycle-management=start_only

spring.mvc.problemdetails.enabled=true

spring.threads.virtual.enabled=true

#spring.jackson.datatype.datetime.write-dates-as-timestamps=false
#spring.jackson.datatype.datetime.read-date-timestamps-as-nanoseconds=false