spring.application.name=@project.name@

server.port=@coupon_service.port@
coupon_service.uri=@coupon_service.uri@

spring.docker.compose.enabled=true
spring.docker.compose.file=@project.basedir@/compose.yaml
spring.docker.compose.lifecycle-management=start_only