spring.application.name=order_service

external.services.url.billing=http://localhost:8081
external.services.url.customer=http://localhost:8082
external.services.url.payment=http://localhost:8083
external.services.url.product=http://localhost:8084
external.services.url.shipping=http://localhost:8085
