spring.application.name=order_service

external.services.url.billing=http://localhost:8081/@billing_service.uri@
external.services.url.customer=http://localhost:8082/@customer_service.uri@
external.services.url.payment=http://localhost:8084/@payment_service.uri@
external.services.url.product=http://localhost:8085/@product_service.uri@
external.services.url.shipping=http://localhost:8086/@shipping_service.uri@
external.services.url.coupon=http://localhost:@coupon_service.port@@coupon_service.uri@


spring.docker.compose.enabled=false
