spring.application.name=@project.name@

server.port=@billing_service.port@
POSTGRES_PORT=@billing_service.postgres.port@

spring.docker.compose.enabled=true
spring.docker.compose.file=@project.basedir@/compose.yaml
spring.docker.compose.lifecycle-management=start_and_stop

