spring:
  application:
    name: @project.name@
  docker:
    compose:
      enabled: false
      file: ${project.basedir}/compose.yaml

server:
  port: 8081

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java: 25

project:
  basedir: @project.basedir@
