spring.application.name=bank_user

spring.docker.compose.enabled=false
spring.docker.compose.file=@project.basedir@/../bank_customer/compose.yaml

server.port=@bank_user.port@
bank_user_uri=@bank_user.uri@