spring.application.name=bank_user

spring.docker.compose.enabled=false
spring.docker.compose.file=@parent.pom.basedir@/sb4_compose.yaml

server.port=@bank_user.port@
bank_user_uri=@bank_user.uri@

#oauth_client_id=hjTl1iI5tpxpZl9oViusNmKzCyjERCXF
#oauth_client_secret=fT3URR4VXkgDN83Dia_Ap-pxVsxZAyCMyO_aKozj7YmWa4EGeUrQ6Q4LSIVycfKm

auth0.mgmt.client-id=YVmDw2geXIZvYqtcmM1glicJCSuWo3eI
auth0.mgmt.client-secret=RE9pyGY1r2WBF96VHnrdIEAMgGh62-04zoSiYFmcopCXLtSWIqh7hGY8Zqa35Rtx
auth0.mgmt.tenant-domain=https://dev-fzlgbfhigtmlgz55.us.auth0.com
auth0.mgmt.audience=${auth0.mgmt.tenant-domain}/api/v2/
auth0.mgmt.token-endpoint=${auth0.mgmt.tenant-domain}/oauth/token
auth0.mgmt.grant-type=client_credentials

# Enable Hazelcast as Hibernate's second-level cache
# For details - https://docs.hazelcast.com/hazelcast/5.7/spring/hibernate
spring.jpa.properties.hiberate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=com.hazelcast.hibernate.HazelcastCacheRegionFactory
spring.jpa.properties.hibernate.cache.hazlecast.instance_name=hazelcast_instance

spring.jpa.properties.javax.persistence.sharedCache.mode=ENABLE_SELECTIVE
