spring.application.name=bank_user

spring.docker.compose.enabled=false
spring.docker.compose.file=@project.basedir@/../bank_customer/compose.yaml

server.port=@bank_user.port@
bank_user_uri=@bank_user.uri@


#oauth_client_id=hjTl1iI5tpxpZl9oViusNmKzCyjERCXF
#oauth_client_secret=fT3URR4VXkgDN83Dia_Ap-pxVsxZAyCMyO_aKozj7YmWa4EGeUrQ6Q4LSIVycfKm
#oauth_audience=http://localhost:9091/api/v1