spring.application.name=@project.name@

server.port=@payment_service.port@
payment_service.uri=@payment_service.port@

spring.docker.compose.file=@project.basedir@/compose.yaml

logging.level.root=info

management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]