spring.application.name=oauth2_0_rs

server.port=@resource_server.port@
resource_server_uri=@resource_server.uri@

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-fzlgbfhigtmlgz55.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=http://localhost:9091/api/v1

spring.docker.compose.enabled=false