spring.application.name=bank_customer

bank_customer_uri=@bank_customer.uri@
server.port=@bank_customer.port@

spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.enabled=false
spring.docker.compose.skip.in-tests=true
spring.docker.compose.file=@project.basedir@/compose.yaml
spring.jpa.hibernate.ddl-auto=none

spring.jpa.open-in-view=false

spring.threads.virtual.enabled=true

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.completion-mode=archive

server.tomcat.threads.max=500
server.tomcat.accept-count=1000
server.tomcat.max-connections=10000

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

async.request.processing.header=@async_processing.header@