spring.application.name=bank_customer

info.app.name=@project.name@
info.app.description=@project.description@
info.app.version=@project.version@
info.app.url=${bank_customer_uri}

bank_customer_uri=@bank_customer.uri@
server.port=@bank_customer.port@

spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.enabled=false
spring.docker.compose.skip.in-tests=true
spring.docker.compose.file=@project.basedir@/compose.yaml
spring.jpa.hibernate.ddl-auto=none

spring.jpa.open-in-view=false

spring.threads.virtual.enabled=true

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.completion-mode=archive

server.tomcat.threads.max=500
server.tomcat.accept-count=1000
server.tomcat.max-connections=10000

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.jdbc.time_zone=Australia/Sydney

async.request.processing.header=@async_processing.header@

management.endpoints.web.base-path=/actuator
management.server.port=10000

management.endpoint.health.logging.slow-indicator-threshold=5s
management.endpoint.health.probes.enabled=true

management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=env,beans

management.info.env.enabled=true
management.endpoint.auditevents.access=unrestricted
management.endpoint.health.show-details=always
management.endpoint.configprops.access=unrestricted
management.endpoint.configprops.show-values=always
management.endpoint.env.show-values=always